package de.gts.redrail.game.constants;

public interface GermanCityName {

    public static String[] fickStadte = {
        "AACH", "AACHEN", "AALEN", "ABENBERG", "ABENSBERG", "ACHERN", "ACHIM", "ADELSHEIM", "ADORF_VOGTL",
        "AHAUS", "AHLEN", "AHRENSBURG", "AICHACH", "AKEN", "ALBSTADT", "ALFELD", "ALLENDORF", "ALLERSBERG",
        "ALSDORF", "ALSFELD", "ALTENA", "ALTENBERG", "ALTENBURG", "ALTENTREPTOW", "ALTLANDSBERG",
        "ALTDORF_BEI_NUERNBERG", "ALTENSTEIG", "ALTOETTING", "ALZENAU", "AMBERG", "AMORBACH", "ANDERNACH",
        "ANGERMUENDE", "ANKLAM", "ANNABERG_BUCHHOLZ", "ANNWEILER", "ANSBACH", "APOLDA", "ARNSBERG", "ARNSTADT",
        "ASCHAFFENBURG", "ASCHERSLEBEN", "ASPERG", "ATTENDORN", "AUB", "AUE_BAD_SCHLEMA", "AUERBACH",
        "AUGSBURG", "AUGUSTUSBURG", "AURICH", "BABENHAUSEN", "BACKNANG", "BAD_AIBLING", "BAD_BERLEBURG",
        "BAD_DUERKHEIM", "BAD_ESSEN", "BAD_FALLINGBOSTEL", "BAD_GANDERSHEIM", "BAD_HARZBURG",
        "BAD_HOMBURG_VOR_DER_HOEHE", "BAD_HONNEF", "BAD_KISSINGEN", "BAD_KREUZNACH", "BAD_LANGENSALZA",
        "BAD_LAUCHSTAEDT", "BAD_LIEBENWERDA", "BAD_MERGENTHEIM", "BAD_MUENDER", "BAD_NAUHEIM",
        "BAD_NENNDORF", "BAD_NEUSTADT_AN_DER_SAALE", "BAD_OLDESLOE", "BAD_PYRMONT", "BAD_RAPPENAU",
        "BAD_REICHENHALL", "BAD_SALZDETFURTH", "BAD_SALZUFLEN", "BAD_SAECKINGEN", "BAD_SAULGAU",
        "BAD_SCHANDAU", "BAD_SCHWARTAU", "BAD_SEGEBERG", "BAD_SODEN_AM_TAUNUS", "BAD_SODEN_SALMUENSTER",
        "BAD_STAFFELSTEIN", "BAD_TOELZ", "BAD_VILBEL", "BAD_WALDSEE", "BAD_WILDBAD", "BAD_WILDUNGEN",
        "BAD_WILSNACK", "BAD_WIMPFEN", "BAD_WINDSHEIM", "BAD_WOERISHOFEN", "BAD_WUENNENBERG",
        "BAD_WURZACH", "BADEN_BADEN", "BAESWEILER", "BAIERSDORF", "BALINGEN", "BALLENSTEDT", "BALVE",
        "BAMBERG", "BARBY", "BARGTEHEIDE", "BARMSTEDT", "BAERNAU", "BARNTRUP", "BARSINGHAUSEN", "BARTH",
        "BARUTH_MARK", "BASSUM", "BATTENBERG", "BAUMHOLDER", "BAUNACH", "BAUNATAL", "BAUTZEN", "BAYREUTH",
        "BEBRA", "BECKUM", "BEDBURG", "BEELITZ", "BEESKOW", "BEILNGRIES", "BEILSTEIN", "BELGERN_SCHILDAU",
        "BENDORF", "BENSHEIM", "BERCHING", "BERGA_WUENSCHENDORF", "BERGEN", "BERGEN_AUF_RUEGEN", "BERGHEIM",
        "BERGISCH_GLADBACH", "BERGKAMEN", "BERGNEUSTADT", "BERLIN", "BERNAU_BEI_BERLIN", "BERNBURG",
        "BERNKASTEL_KUES", "BERNSDORF", "BERNSTADT_A_D_EIGEN", "BERSENBRUECK", "BESIGHEIM", "BETZDORF",
        "BETZENSTEIN", "BEVERUNGEN", "BEXBACH", "BIBERACH_AN_DER_RISS", "BIEDENKOPF", "BIELEFELD",
        "BIESENTHAL", "BIETIGHEIM_BISSINGEN", "BILLERBECK", "BINGEN_AM_RHEIN", "BIRKENFELD",
        "BISCHOFSHEIM_IN_DER_RHOEN", "BISCHOFWERDA", "BISMARK", "BITBURG", "BITTERFELD_WOLFEN",
        "BLANKENBURG", "BLANKENHAIN"
    };
}